# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.buy_btc_response_palm_pay_notify_entity import BuyBtcResponsePalmPayNotifyEntity

class TestBuyBtcResponsePalmPayNotifyEntity(unittest.TestCase):
    """BuyBtcResponsePalmPayNotifyEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuyBtcResponsePalmPayNotifyEntity:
        """Test BuyBtcResponsePalmPayNotifyEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuyBtcResponsePalmPayNotifyEntity`
        """
        model = BuyBtcResponsePalmPayNotifyEntity()
        if include_optional:
            return BuyBtcResponsePalmPayNotifyEntity(
                code = '',
                message = '',
                detail = '',
                data = buybtcpay.models.palm_pay_notify_entity.PalmPayNotifyEntity(
                    id = '', 
                    create_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    merchant_id = '', 
                    order_id = '', 
                    order_no = '', 
                    amount = '', 
                    currency = 'NGN', 
                    order_status = 0, 
                    complete_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    error_code = '', 
                    sign = '', 
                    payer_bank_code = '', 
                    payer_bank_name = '', 
                    payer_account_no = '', 
                    payer_account_name = '', )
            )
        else:
            return BuyBtcResponsePalmPayNotifyEntity(
        )
        """

    def testBuyBtcResponsePalmPayNotifyEntity(self):
        """Test BuyBtcResponsePalmPayNotifyEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
