# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.api.open_payout_api import OpenPayoutApi


class TestOpenPayoutApi(unittest.TestCase):
    """OpenPayoutApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenPayoutApi()

    def tearDown(self) -> None:
        pass

    def test_pagination7(self) -> None:
        """Test case for pagination7

        用户代付列表
        """
        pass

    def test_payout1(self) -> None:
        """Test case for payout1

        用户代付接口
        """
        pass


if __name__ == '__main__':
    unittest.main()
