# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.pay_pagination_query_palm_pay_virtual_account_query import PayPaginationQueryPalmPayVirtualAccountQuery

class TestPayPaginationQueryPalmPayVirtualAccountQuery(unittest.TestCase):
    """PayPaginationQueryPalmPayVirtualAccountQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayPaginationQueryPalmPayVirtualAccountQuery:
        """Test PayPaginationQueryPalmPayVirtualAccountQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayPaginationQueryPalmPayVirtualAccountQuery`
        """
        model = PayPaginationQueryPalmPayVirtualAccountQuery()
        if include_optional:
            return PayPaginationQueryPalmPayVirtualAccountQuery(
                current = 1,
                size = 1,
                query = buybtcpay.models.palm_pay_virtual_account_query.PalmPayVirtualAccountQuery(
                    id = '', 
                    order_by_create_at = '', 
                    create_at_since = '', 
                    create_at_until = '', 
                    virtual_account_name = '', 
                    virtual_account_no = '', 
                    account_status = 'Disabled', 
                    identity_type = 'personal', 
                    email = '', )
            )
        else:
            return PayPaginationQueryPalmPayVirtualAccountQuery(
        )
        """

    def testPayPaginationQueryPalmPayVirtualAccountQuery(self):
        """Test PayPaginationQueryPalmPayVirtualAccountQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
