# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.buy_btc_response_pay_pagination_wallet_permission_entity import BuyBtcResponsePayPaginationWalletPermissionEntity

class TestBuyBtcResponsePayPaginationWalletPermissionEntity(unittest.TestCase):
    """BuyBtcResponsePayPaginationWalletPermissionEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuyBtcResponsePayPaginationWalletPermissionEntity:
        """Test BuyBtcResponsePayPaginationWalletPermissionEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuyBtcResponsePayPaginationWalletPermissionEntity`
        """
        model = BuyBtcResponsePayPaginationWalletPermissionEntity()
        if include_optional:
            return BuyBtcResponsePayPaginationWalletPermissionEntity(
                code = '',
                message = '',
                detail = '',
                data = buybtcpay.models.pay_pagination_wallet_permission_entity.PayPaginationWalletPermissionEntity(
                    total = 56, 
                    current = 56, 
                    size = 56, 
                    pages = 56, 
                    latest = True, 
                    data = [
                        buybtcpay.models.钱包权限控制.钱包权限控制(
                            id = '', 
                            create_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            wallet_id = 56, 
                            permission = 1, 
                            merchant_id = '', )
                        ], )
            )
        else:
            return BuyBtcResponsePayPaginationWalletPermissionEntity(
        )
        """

    def testBuyBtcResponsePayPaginationWalletPermissionEntity(self):
        """Test BuyBtcResponsePayPaginationWalletPermissionEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
