# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.query_pay_status_data import QueryPayStatusData

class TestQueryPayStatusData(unittest.TestCase):
    """QueryPayStatusData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryPayStatusData:
        """Test QueryPayStatusData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryPayStatusData`
        """
        model = QueryPayStatusData()
        if include_optional:
            return QueryPayStatusData(
                amount = 56,
                fee = buybtcpay.models.fee.Fee(
                    amount = 56, ),
                order_no = '',
                order_id = '',
                order_status = 56,
                session_id = '',
                message = '',
                error_msg = '',
                create_time = 56,
                completed_time = 56
            )
        else:
            return QueryPayStatusData(
        )
        """

    def testQueryPayStatusData(self):
        """Test QueryPayStatusData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
