# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_approval_dto_create_merchant_recharge_approval_dto import CreateApprovalDtoCreateMerchantRechargeApprovalDto

class TestCreateApprovalDtoCreateMerchantRechargeApprovalDto(unittest.TestCase):
    """CreateApprovalDtoCreateMerchantRechargeApprovalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApprovalDtoCreateMerchantRechargeApprovalDto:
        """Test CreateApprovalDtoCreateMerchantRechargeApprovalDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApprovalDtoCreateMerchantRechargeApprovalDto`
        """
        model = CreateApprovalDtoCreateMerchantRechargeApprovalDto()
        if include_optional:
            return CreateApprovalDtoCreateMerchantRechargeApprovalDto(
                applicant_id = '',
                business_id = '',
                approval_type = 0,
                content = buybtcpay.models.创建商户充值审批单.创建商户充值审批单(
                    amount = '', 
                    currency_type = 'NGN', 
                    merchant_id = '', 
                    note = '', )
            )
        else:
            return CreateApprovalDtoCreateMerchantRechargeApprovalDto(
                approval_type = 0,
        )
        """

    def testCreateApprovalDtoCreateMerchantRechargeApprovalDto(self):
        """Test CreateApprovalDtoCreateMerchantRechargeApprovalDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
