# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_virtual_account_recharge_approval_dto import CreateVirtualAccountRechargeApprovalDto

class TestCreateVirtualAccountRechargeApprovalDto(unittest.TestCase):
    """CreateVirtualAccountRechargeApprovalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateVirtualAccountRechargeApprovalDto:
        """Test CreateVirtualAccountRechargeApprovalDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateVirtualAccountRechargeApprovalDto`
        """
        model = CreateVirtualAccountRechargeApprovalDto()
        if include_optional:
            return CreateVirtualAccountRechargeApprovalDto(
                amount = '',
                currency_type = 'NGN',
                wallet_id = '',
                note = '',
                dmerchant_id = ''
            )
        else:
            return CreateVirtualAccountRechargeApprovalDto(
                amount = '',
                currency_type = 'NGN',
                wallet_id = '',
        )
        """

    def testCreateVirtualAccountRechargeApprovalDto(self):
        """Test CreateVirtualAccountRechargeApprovalDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
