# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.api.open_exchange_rate_api import OpenExchangeRateApi


class TestOpenExchangeRateApi(unittest.TestCase):
    """OpenExchangeRateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenExchangeRateApi()

    def tearDown(self) -> None:
        pass

    def test_currency_conversion(self) -> None:
        """Test case for currency_conversion

        币种转换
        """
        pass


if __name__ == '__main__':
    unittest.main()
