# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_merchant_self_recharge_dto import CreateMerchantSelfRechargeDto

class TestCreateMerchantSelfRechargeDto(unittest.TestCase):
    """CreateMerchantSelfRechargeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMerchantSelfRechargeDto:
        """Test CreateMerchantSelfRechargeDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMerchantSelfRechargeDto`
        """
        model = CreateMerchantSelfRechargeDto()
        if include_optional:
            return CreateMerchantSelfRechargeDto(
                source_currency = 'NGN',
                source_amount = '68072888001528021798096225500',
                target_currency = 'NGN',
                exchange_rate_id = '',
                exchange_rate = '',
                exchange_rate_source = '1',
                payee_wallet_address = '',
                target_amount = '',
                amount = '',
                merchant_id = '',
                note = '',
                timeout = 56,
                user_submited = True,
                received = True
            )
        else:
            return CreateMerchantSelfRechargeDto(
                source_currency = 'NGN',
                source_amount = '68072888001528021798096225500',
                target_currency = 'NGN',
                merchant_id = '',
                note = '',
        )
        """

    def testCreateMerchantSelfRechargeDto(self):
        """Test CreateMerchantSelfRechargeDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
