# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_usdt_self_recharge_approval_dto import CreateUSDTSelfRechargeApprovalDto

class TestCreateUSDTSelfRechargeApprovalDto(unittest.TestCase):
    """CreateUSDTSelfRechargeApprovalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUSDTSelfRechargeApprovalDto:
        """Test CreateUSDTSelfRechargeApprovalDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUSDTSelfRechargeApprovalDto`
        """
        model = CreateUSDTSelfRechargeApprovalDto()
        if include_optional:
            return CreateUSDTSelfRechargeApprovalDto(
                source_amount = '68072888001528021798096225500',
                exchange_rate_id = '',
                exchange_rate = '',
                exchange_rate_source = '1',
                payee_wallet_address = '',
                target_amount = '',
                amount = '',
                wallet_id = '',
                note = '',
                timeout = 56,
                user_submitted = True,
                received = True
            )
        else:
            return CreateUSDTSelfRechargeApprovalDto(
                source_amount = '68072888001528021798096225500',
                wallet_id = '',
        )
        """

    def testCreateUSDTSelfRechargeApprovalDto(self):
        """Test CreateUSDTSelfRechargeApprovalDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
