# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.pay_pagination_merchant_entity_dto import PayPaginationMerchantEntityDto

class TestPayPaginationMerchantEntityDto(unittest.TestCase):
    """PayPaginationMerchantEntityDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayPaginationMerchantEntityDto:
        """Test PayPaginationMerchantEntityDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayPaginationMerchantEntityDto`
        """
        model = PayPaginationMerchantEntityDto()
        if include_optional:
            return PayPaginationMerchantEntityDto(
                total = 56,
                current = 56,
                size = 56,
                pages = 56,
                latest = True,
                data = [
                    buybtcpay.models.merchant_entity_dto.MerchantEntityDto(
                        id = 56, 
                        create_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 0, 
                        merchant_id = '', 
                        public_key = '', 
                        name = '', 
                        email = '', 
                        role = 0, 
                        merchant_status = 0, 
                        palm_pay_virtual_account_no = '', 
                        note = '', 
                        tag = '', 
                        virtual_account_id = 56, )
                    ]
            )
        else:
            return PayPaginationMerchantEntityDto(
        )
        """

    def testPayPaginationMerchantEntityDto(self):
        """Test PayPaginationMerchantEntityDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
