# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_approval_dto_create_virtual_account_recharge_approval_dto import CreateApprovalDtoCreateVirtualAccountRechargeApprovalDto

class TestCreateApprovalDtoCreateVirtualAccountRechargeApprovalDto(unittest.TestCase):
    """CreateApprovalDtoCreateVirtualAccountRechargeApprovalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApprovalDtoCreateVirtualAccountRechargeApprovalDto:
        """Test CreateApprovalDtoCreateVirtualAccountRechargeApprovalDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApprovalDtoCreateVirtualAccountRechargeApprovalDto`
        """
        model = CreateApprovalDtoCreateVirtualAccountRechargeApprovalDto()
        if include_optional:
            return CreateApprovalDtoCreateVirtualAccountRechargeApprovalDto(
                applicant_id = '',
                business_id = '',
                approval_type = 0,
                content = buybtcpay.models.创建虚拟账户充值审批单.创建虚拟账户充值审批单(
                    amount = '', 
                    currency_type = 'NGN', 
                    wallet_id = '', 
                    note = '', 
                    dmerchant_id = '', )
            )
        else:
            return CreateApprovalDtoCreateVirtualAccountRechargeApprovalDto(
                approval_type = 0,
        )
        """

    def testCreateApprovalDtoCreateVirtualAccountRechargeApprovalDto(self):
        """Test CreateApprovalDtoCreateVirtualAccountRechargeApprovalDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
