# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.merchant_money_usage_statistics_req import MerchantMoneyUsageStatisticsReq

class TestMerchantMoneyUsageStatisticsReq(unittest.TestCase):
    """MerchantMoneyUsageStatisticsReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantMoneyUsageStatisticsReq:
        """Test MerchantMoneyUsageStatisticsReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantMoneyUsageStatisticsReq`
        """
        model = MerchantMoneyUsageStatisticsReq()
        if include_optional:
            return MerchantMoneyUsageStatisticsReq(
                merchant_id = '',
                start_time = '',
                end_time = '',
                group_by_hour = True,
                currency = 'NGN'
            )
        else:
            return MerchantMoneyUsageStatisticsReq(
                merchant_id = '',
                start_time = '',
                end_time = '',
                currency = 'NGN',
        )
        """

    def testMerchantMoneyUsageStatisticsReq(self):
        """Test MerchantMoneyUsageStatisticsReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
