# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_reversal_merchant_to_merchant_approval_dto import CreateReversalMerchantToMerchantApprovalDto

class TestCreateReversalMerchantToMerchantApprovalDto(unittest.TestCase):
    """CreateReversalMerchantToMerchantApprovalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateReversalMerchantToMerchantApprovalDto:
        """Test CreateReversalMerchantToMerchantApprovalDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateReversalMerchantToMerchantApprovalDto`
        """
        model = CreateReversalMerchantToMerchantApprovalDto()
        if include_optional:
            return CreateReversalMerchantToMerchantApprovalDto(
                payer_merchant_id = '',
                payee_merchant_id = '',
                amount = '',
                currency_type = 'NGN',
                note = ''
            )
        else:
            return CreateReversalMerchantToMerchantApprovalDto(
                payer_merchant_id = '',
                payee_merchant_id = '',
                amount = '',
                currency_type = 'NGN',
        )
        """

    def testCreateReversalMerchantToMerchantApprovalDto(self):
        """Test CreateReversalMerchantToMerchantApprovalDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
