# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.approval_pagination_query import ApprovalPaginationQuery

class TestApprovalPaginationQuery(unittest.TestCase):
    """ApprovalPaginationQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApprovalPaginationQuery:
        """Test ApprovalPaginationQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApprovalPaginationQuery`
        """
        model = ApprovalPaginationQuery()
        if include_optional:
            return ApprovalPaginationQuery(
                id = '',
                order_by_create_at = '',
                create_at_since = '',
                create_at_until = '',
                applicant_id = '',
                approval_status = 0,
                approval_time_since = '',
                approval_time_until = '',
                approval_type = 0,
                approval_types = [
                    0
                    ],
                business_id = ''
            )
        else:
            return ApprovalPaginationQuery(
        )
        """

    def testApprovalPaginationQuery(self):
        """Test ApprovalPaginationQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
