# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.self_service_approval_submited_dto import SelfServiceApprovalSubmitedDto

class TestSelfServiceApprovalSubmitedDto(unittest.TestCase):
    """SelfServiceApprovalSubmitedDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SelfServiceApprovalSubmitedDto:
        """Test SelfServiceApprovalSubmitedDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SelfServiceApprovalSubmitedDto`
        """
        model = SelfServiceApprovalSubmitedDto()
        if include_optional:
            return SelfServiceApprovalSubmitedDto(
                approval_id = '',
                submited = True
            )
        else:
            return SelfServiceApprovalSubmitedDto(
        )
        """

    def testSelfServiceApprovalSubmitedDto(self):
        """Test SelfServiceApprovalSubmitedDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
