# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.api.open_wallet_api import OpenWalletApi


class TestOpenWalletApi(unittest.TestCase):
    """OpenWalletApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenWalletApi()

    def tearDown(self) -> None:
        pass

    def test_aggregation(self) -> None:
        """Test case for aggregation

        钱包金额汇总
        """
        pass

    def test_find_by_currency(self) -> None:
        """Test case for find_by_currency

        查询商户指定币种钱包
        """
        pass

    def test_find_by_merchant_id(self) -> None:
        """Test case for find_by_merchant_id

        查询商户所有钱包
        """
        pass

    def test_find_by_type_and_currency(self) -> None:
        """Test case for find_by_type_and_currency

        查询商户指定币种、类型的钱包
        """
        pass

    def test_pagination4(self) -> None:
        """Test case for pagination4

        分页查询商户钱包
        """
        pass

    def test_query_merchant_wallet_info(self) -> None:
        """Test case for query_merchant_wallet_info

        查询钱包信息
        """
        pass


if __name__ == '__main__':
    unittest.main()
