# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.merchant_wallet_count_query import MerchantWalletCountQuery

class TestMerchantWalletCountQuery(unittest.TestCase):
    """MerchantWalletCountQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantWalletCountQuery:
        """Test MerchantWalletCountQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantWalletCountQuery`
        """
        model = MerchantWalletCountQuery()
        if include_optional:
            return MerchantWalletCountQuery(
                tag = [
                    ''
                    ],
                currency = 'NGN'
            )
        else:
            return MerchantWalletCountQuery(
        )
        """

    def testMerchantWalletCountQuery(self):
        """Test MerchantWalletCountQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
