# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_approval_dto_create_frozen_approval_dto import CreateApprovalDtoCreateFrozenApprovalDto

class TestCreateApprovalDtoCreateFrozenApprovalDto(unittest.TestCase):
    """CreateApprovalDtoCreateFrozenApprovalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApprovalDtoCreateFrozenApprovalDto:
        """Test CreateApprovalDtoCreateFrozenApprovalDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApprovalDtoCreateFrozenApprovalDto`
        """
        model = CreateApprovalDtoCreateFrozenApprovalDto()
        if include_optional:
            return CreateApprovalDtoCreateFrozenApprovalDto(
                applicant_id = '',
                business_id = '',
                approval_type = 0,
                content = buybtcpay.models.create_frozen_approval_dto.CreateFrozenApprovalDto(
                    merchant_id = '', 
                    amount = '', 
                    currency_type = 'NGN', 
                    note = '', )
            )
        else:
            return CreateApprovalDtoCreateFrozenApprovalDto(
                approval_type = 0,
        )
        """

    def testCreateApprovalDtoCreateFrozenApprovalDto(self):
        """Test CreateApprovalDtoCreateFrozenApprovalDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
