# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.api.payout_api import PayoutApi


class TestPayoutApi(unittest.TestCase):
    """PayoutApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PayoutApi()

    def tearDown(self) -> None:
        pass

    def test_open_payout(self) -> None:
        """Test case for open_payout

        """
        pass

    def test_pagination2(self) -> None:
        """Test case for pagination2

        """
        pass

    def test_payout(self) -> None:
        """Test case for payout

        登录商户发起支付
        """
        pass

    def test_withdraw(self) -> None:
        """Test case for withdraw

        登录商户发起提现
        """
        pass


if __name__ == '__main__':
    unittest.main()
