# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.set_merchant_public_key_dto import SetMerchantPublicKeyDto

class TestSetMerchantPublicKeyDto(unittest.TestCase):
    """SetMerchantPublicKeyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetMerchantPublicKeyDto:
        """Test SetMerchantPublicKeyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetMerchantPublicKeyDto`
        """
        model = SetMerchantPublicKeyDto()
        if include_optional:
            return SetMerchantPublicKeyDto(
                public_key = ''
            )
        else:
            return SetMerchantPublicKeyDto(
                public_key = '',
        )
        """

    def testSetMerchantPublicKeyDto(self):
        """Test SetMerchantPublicKeyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
