# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.buy_btc_response_pay_pagination_prepayment_order_entity import BuyBtcResponsePayPaginationPrepaymentOrderEntity

class TestBuyBtcResponsePayPaginationPrepaymentOrderEntity(unittest.TestCase):
    """BuyBtcResponsePayPaginationPrepaymentOrderEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuyBtcResponsePayPaginationPrepaymentOrderEntity:
        """Test BuyBtcResponsePayPaginationPrepaymentOrderEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuyBtcResponsePayPaginationPrepaymentOrderEntity`
        """
        model = BuyBtcResponsePayPaginationPrepaymentOrderEntity()
        if include_optional:
            return BuyBtcResponsePayPaginationPrepaymentOrderEntity(
                code = '',
                message = '',
                detail = '',
                data = buybtcpay.models.pay_pagination_prepayment_order_entity.PayPaginationPrepaymentOrderEntity(
                    total = 56, 
                    current = 56, 
                    size = 56, 
                    pages = 56, 
                    latest = True, 
                    data = [
                        buybtcpay.models.prepayment_order_entity.PrepaymentOrderEntity(
                            id = '', 
                            create_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            business_id = '', 
                            channel_id = '', 
                            merchant_id = '', 
                            type = 0, 
                            amount = buybtcpay.models.buy_btc_money_json_value.BuyBtcMoneyJsonValue(
                                currency = '', ), 
                            fee = buybtcpay.models.buy_btc_money_json_value.BuyBtcMoneyJsonValue(
                                currency = '', ), 
                            fee_to_channel = 1.337, 
                            fee_to_buy_btc = 1.337, 
                            order_status = 0, 
                            payment_order_id = 56, 
                            wallet_id = 56, 
                            wallet_type = '1', 
                            bill_id = 56, 
                            version = 56, )
                        ], )
            )
        else:
            return BuyBtcResponsePayPaginationPrepaymentOrderEntity(
        )
        """

    def testBuyBtcResponsePayPaginationPrepaymentOrderEntity(self):
        """Test BuyBtcResponsePayPaginationPrepaymentOrderEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
