# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.buy_btc_response_pay_pagination_merchant_bill_entity import BuyBtcResponsePayPaginationMerchantBillEntity

class TestBuyBtcResponsePayPaginationMerchantBillEntity(unittest.TestCase):
    """BuyBtcResponsePayPaginationMerchantBillEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuyBtcResponsePayPaginationMerchantBillEntity:
        """Test BuyBtcResponsePayPaginationMerchantBillEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuyBtcResponsePayPaginationMerchantBillEntity`
        """
        model = BuyBtcResponsePayPaginationMerchantBillEntity()
        if include_optional:
            return BuyBtcResponsePayPaginationMerchantBillEntity(
                code = '',
                message = '',
                detail = '',
                data = buybtcpay.models.pay_pagination_merchant_bill_entity.PayPaginationMerchantBillEntity(
                    total = 56, 
                    current = 56, 
                    size = 56, 
                    pages = 56, 
                    latest = True, 
                    data = [
                        buybtcpay.models.merchant_bill_entity.MerchantBillEntity(
                            id = '', 
                            create_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            business_id = '', 
                            merchant_id = '', 
                            channel_id = '', 
                            business_type = 1, 
                            account_type = 1, 
                            account_no = '', 
                            direction = 1, 
                            amount = buybtcpay.models.buy_btc_money_json_value.BuyBtcMoneyJsonValue(
                                currency = '', ), 
                            counterparty_account_type = 1, 
                            counterparty_account_no = '', 
                            bill_status = 0, 
                            extra = buybtcpay.models.merchant_bill_extra.MerchantBillExtra(
                                type = 1, ), )
                        ], )
            )
        else:
            return BuyBtcResponsePayPaginationMerchantBillEntity(
        )
        """

    def testBuyBtcResponsePayPaginationMerchantBillEntity(self):
        """Test BuyBtcResponsePayPaginationMerchantBillEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
