# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.pay_pagination_query_merchant_bill_query import PayPaginationQueryMerchantBillQuery

class TestPayPaginationQueryMerchantBillQuery(unittest.TestCase):
    """PayPaginationQueryMerchantBillQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayPaginationQueryMerchantBillQuery:
        """Test PayPaginationQueryMerchantBillQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayPaginationQueryMerchantBillQuery`
        """
        model = PayPaginationQueryMerchantBillQuery()
        if include_optional:
            return PayPaginationQueryMerchantBillQuery(
                current = 1,
                size = 1,
                query = buybtcpay.models.merchant_bill_query.MerchantBillQuery(
                    id = '', 
                    order_by_create_at = '', 
                    create_at_since = '', 
                    create_at_until = '', 
                    from_channel = '', 
                    operator = '', 
                    business_ids = [
                        ''
                        ], 
                    business_id = '', 
                    channel_id = '', 
                    merchant_id = [
                        ''
                        ], 
                    business_type = [
                        1
                        ], 
                    account_type = [
                        1
                        ], 
                    counterparty_account_type = [
                        1
                        ], 
                    account_no = '', 
                    counterparty_account_no = '', 
                    direction = [
                        1
                        ], 
                    bill_status = [
                        0
                        ], 
                    currency = [
                        'NGN'
                        ], 
                    amount = [
                        ''
                        ], 
                    wallet_type = '1', 
                    wallet_id = [
                        ''
                        ], )
            )
        else:
            return PayPaginationQueryMerchantBillQuery(
        )
        """

    def testPayPaginationQueryMerchantBillQuery(self):
        """Test PayPaginationQueryMerchantBillQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
