# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.buy_btc_money_json_value import BuyBtcMoneyJsonValue

class TestBuyBtcMoneyJsonValue(unittest.TestCase):
    """BuyBtcMoneyJsonValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuyBtcMoneyJsonValue:
        """Test BuyBtcMoneyJsonValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuyBtcMoneyJsonValue`
        """
        model = BuyBtcMoneyJsonValue()
        if include_optional:
            return BuyBtcMoneyJsonValue(
                amount = '',
                currency = ''
            )
        else:
            return BuyBtcMoneyJsonValue(
        )
        """

    def testBuyBtcMoneyJsonValue(self):
        """Test BuyBtcMoneyJsonValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
