# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_approval_dto_create_reversal_platfrom_to_wallet_approval_dto import CreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto

class TestCreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto(unittest.TestCase):
    """CreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto:
        """Test CreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto`
        """
        model = CreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto()
        if include_optional:
            return CreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto(
                applicant_id = '',
                business_id = '',
                approval_type = 0,
                content = buybtcpay.models.create_reversal_platfrom_to_wallet_approval_dto.CreateReversalPlatfromToWalletApprovalDto(
                    wallet_id = '', 
                    amount = '', 
                    note = '', )
            )
        else:
            return CreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto(
                approval_type = 0,
        )
        """

    def testCreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto(self):
        """Test CreateApprovalDtoCreateReversalPlatfromToWalletApprovalDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
