# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.pay_response_query_balance_response import PayResponseQueryBalanceResponse

class TestPayResponseQueryBalanceResponse(unittest.TestCase):
    """PayResponseQueryBalanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayResponseQueryBalanceResponse:
        """Test PayResponseQueryBalanceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayResponseQueryBalanceResponse`
        """
        model = PayResponseQueryBalanceResponse()
        if include_optional:
            return PayResponseQueryBalanceResponse(
                message = '',
                success = True,
                status = '200',
                data = buybtcpay.models.query_balance_response.QueryBalanceResponse(
                    resp_code = '', 
                    resp_msg = '', 
                    data = buybtcpay.models.query_balance_data.QueryBalanceData(
                        available_balance = 56, 
                        frozen_balance = 56, 
                        current_balance = 56, 
                        un_settle_balance = 56, ), 
                    success = True, )
            )
        else:
            return PayResponseQueryBalanceResponse(
        )
        """

    def testPayResponseQueryBalanceResponse(self):
        """Test PayResponseQueryBalanceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
