# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.pay_pagination_query_wallet_permission_query import PayPaginationQueryWalletPermissionQuery

class TestPayPaginationQueryWalletPermissionQuery(unittest.TestCase):
    """PayPaginationQueryWalletPermissionQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayPaginationQueryWalletPermissionQuery:
        """Test PayPaginationQueryWalletPermissionQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayPaginationQueryWalletPermissionQuery`
        """
        model = PayPaginationQueryWalletPermissionQuery()
        if include_optional:
            return PayPaginationQueryWalletPermissionQuery(
                current = 1,
                size = 1,
                query = buybtcpay.models.wallet_permission_query.WalletPermissionQuery(
                    id = '', 
                    order_by_create_at = '', 
                    create_at_since = '', 
                    create_at_until = '', 
                    wallet_id = [
                        ''
                        ], 
                    permissions = [
                        1
                        ], 
                    merchant_id = [
                        ''
                        ], )
            )
        else:
            return PayPaginationQueryWalletPermissionQuery(
        )
        """

    def testPayPaginationQueryWalletPermissionQuery(self):
        """Test PayPaginationQueryWalletPermissionQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
