# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.buy_btc_response_virtual_account_label_update_response import BuyBtcResponseVirtualAccountLabelUpdateResponse

class TestBuyBtcResponseVirtualAccountLabelUpdateResponse(unittest.TestCase):
    """BuyBtcResponseVirtualAccountLabelUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuyBtcResponseVirtualAccountLabelUpdateResponse:
        """Test BuyBtcResponseVirtualAccountLabelUpdateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuyBtcResponseVirtualAccountLabelUpdateResponse`
        """
        model = BuyBtcResponseVirtualAccountLabelUpdateResponse()
        if include_optional:
            return BuyBtcResponseVirtualAccountLabelUpdateResponse(
                code = '',
                message = '',
                detail = '',
                data = buybtcpay.models.virtual_account_label_update_response.VirtualAccountLabelUpdateResponse(
                    resp_code = '', 
                    resp_msg = '', 
                    status = True, 
                    success = True, )
            )
        else:
            return BuyBtcResponseVirtualAccountLabelUpdateResponse(
        )
        """

    def testBuyBtcResponseVirtualAccountLabelUpdateResponse(self):
        """Test BuyBtcResponseVirtualAccountLabelUpdateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
