# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.query_pay_status_response import QueryPayStatusResponse

class TestQueryPayStatusResponse(unittest.TestCase):
    """QueryPayStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryPayStatusResponse:
        """Test QueryPayStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryPayStatusResponse`
        """
        model = QueryPayStatusResponse()
        if include_optional:
            return QueryPayStatusResponse(
                resp_code = '',
                resp_msg = '',
                data = buybtcpay.models.query_pay_status_data.QueryPayStatusData(
                    currency = '', 
                    amount = 56, 
                    fee = buybtcpay.models.fee.Fee(
                        vat = '', ), 
                    order_no = '', 
                    order_id = '', 
                    order_status = 56, 
                    session_id = '', 
                    message = '', 
                    error_msg = '', 
                    create_time = 56, 
                    completed_time = 56, ),
                success = True
            )
        else:
            return QueryPayStatusResponse(
        )
        """

    def testQueryPayStatusResponse(self):
        """Test QueryPayStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
