# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.api.platform_account_api import PlatformAccountApi


class TestPlatformAccountApi(unittest.TestCase):
    """PlatformAccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlatformAccountApi()

    def tearDown(self) -> None:
        pass

    def test_get_platform_accounts(self) -> None:
        """Test case for get_platform_accounts

        获取平台账户列表
        """
        pass


if __name__ == '__main__':
    unittest.main()
