# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.api.open_testing_api import OpenTestingApi


class TestOpenTestingApi(unittest.TestCase):
    """OpenTestingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenTestingApi()

    def tearDown(self) -> None:
        pass

    def test_idempotency(self) -> None:
        """Test case for idempotency

        Idempotency key
        """
        pass


if __name__ == '__main__':
    unittest.main()
