# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_refund_approval_dto import CreateRefundApprovalDto

class TestCreateRefundApprovalDto(unittest.TestCase):
    """CreateRefundApprovalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRefundApprovalDto:
        """Test CreateRefundApprovalDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRefundApprovalDto`
        """
        model = CreateRefundApprovalDto()
        if include_optional:
            return CreateRefundApprovalDto(
                amount = '',
                currency_type = 'NGN',
                note = ''
            )
        else:
            return CreateRefundApprovalDto(
                amount = '',
                currency_type = 'NGN',
        )
        """

    def testCreateRefundApprovalDto(self):
        """Test CreateRefundApprovalDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
