# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.payment_palm_pay_param import PaymentPalmPayParam

class TestPaymentPalmPayParam(unittest.TestCase):
    """PaymentPalmPayParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentPalmPayParam:
        """Test PaymentPalmPayParam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentPalmPayParam`
        """
        model = PaymentPalmPayParam()
        if include_optional:
            return PaymentPalmPayParam(
                title = '',
                description = '',
                payee_name = '',
                payee_bank_code = '',
                payee_bank_acc_no = '',
                payee_phone_no = '',
                notify_url = '',
                remark = ''
            )
        else:
            return PaymentPalmPayParam(
                payee_bank_code = '',
                payee_bank_acc_no = '',
        )
        """

    def testPaymentPalmPayParam(self):
        """Test PaymentPalmPayParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
