# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.message_lite import MessageLite

class TestMessageLite(unittest.TestCase):
    """MessageLite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageLite:
        """Test MessageLite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageLite`
        """
        model = MessageLite()
        if include_optional:
            return MessageLite(
                serialized_size = 56,
                parser_for_type = buybtcpay.models.parser_message_lite.ParserMessageLite(),
                initialized = True,
                default_instance_for_type = buybtcpay.models.message_lite.MessageLite(
                    serialized_size = 56, 
                    parser_for_type = buybtcpay.models.parser_message_lite.ParserMessageLite(), 
                    initialized = True, 
                    default_instance_for_type = buybtcpay.models.message_lite.MessageLite(
                        serialized_size = 56, 
                        parser_for_type = buybtcpay.models.parser_message_lite.ParserMessageLite(), 
                        initialized = True, ), )
            )
        else:
            return MessageLite(
        )
        """

    def testMessageLite(self):
        """Test MessageLite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
