# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.count_payout_dto import CountPayoutDto

class TestCountPayoutDto(unittest.TestCase):
    """CountPayoutDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CountPayoutDto:
        """Test CountPayoutDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CountPayoutDto`
        """
        model = CountPayoutDto()
        if include_optional:
            return CountPayoutDto(
                time = '',
                count = 56
            )
        else:
            return CountPayoutDto(
        )
        """

    def testCountPayoutDto(self):
        """Test CountPayoutDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
