# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_trade_prepayment_order_dto import CreateTradePrepaymentOrderDto

class TestCreateTradePrepaymentOrderDto(unittest.TestCase):
    """CreateTradePrepaymentOrderDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTradePrepaymentOrderDto:
        """Test CreateTradePrepaymentOrderDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTradePrepaymentOrderDto`
        """
        model = CreateTradePrepaymentOrderDto()
        if include_optional:
            return CreateTradePrepaymentOrderDto(
                verification = buybtcpay.models.verification.Verification(
                    request_id = '', 
                    otp_code = '', 
                    otp_type = '', ),
                request_time = '40123456789101112',
                version = 'v4.072888001528021798096225500850762068629',
                nonce = 'G012345678910111213141516171819202122232425262728293031',
                business_id = '',
                operator = '',
                amount = '',
                currency = 'NGN',
                wallet_id = '',
                auto_choose_wallet = True
            )
        else:
            return CreateTradePrepaymentOrderDto(
                request_time = '40123456789101112',
                version = 'v4.072888001528021798096225500850762068629',
                nonce = 'G012345678910111213141516171819202122232425262728293031',
                business_id = '',
                operator = '',
                amount = '',
                currency = 'NGN',
        )
        """

    def testCreateTradePrepaymentOrderDto(self):
        """Test CreateTradePrepaymentOrderDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
