# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.pay_pagination_query_approval_pagination_query import PayPaginationQueryApprovalPaginationQuery

class TestPayPaginationQueryApprovalPaginationQuery(unittest.TestCase):
    """PayPaginationQueryApprovalPaginationQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayPaginationQueryApprovalPaginationQuery:
        """Test PayPaginationQueryApprovalPaginationQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayPaginationQueryApprovalPaginationQuery`
        """
        model = PayPaginationQueryApprovalPaginationQuery()
        if include_optional:
            return PayPaginationQueryApprovalPaginationQuery(
                current = 1,
                size = 1,
                query = buybtcpay.models.查询审批单.查询审批单(
                    id = '', 
                    order_by_create_at = '', 
                    create_at_since = '', 
                    create_at_until = '', 
                    applicant_id = '', 
                    approval_status = 0, 
                    approval_time_since = '', 
                    approval_time_until = '', 
                    approval_type = 0, 
                    approval_types = [
                        0
                        ], 
                    business_id = '', )
            )
        else:
            return PayPaginationQueryApprovalPaginationQuery(
        )
        """

    def testPayPaginationQueryApprovalPaginationQuery(self):
        """Test PayPaginationQueryApprovalPaginationQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
