# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.pay_response_pagination_approval_entity import PayResponsePaginationApprovalEntity

class TestPayResponsePaginationApprovalEntity(unittest.TestCase):
    """PayResponsePaginationApprovalEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayResponsePaginationApprovalEntity:
        """Test PayResponsePaginationApprovalEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayResponsePaginationApprovalEntity`
        """
        model = PayResponsePaginationApprovalEntity()
        if include_optional:
            return PayResponsePaginationApprovalEntity(
                message = '',
                success = True,
                status = '200',
                data = buybtcpay.models.pay_pagination_approval_entity.PayPaginationApprovalEntity(
                    total = 56, 
                    current = 56, 
                    size = 56, 
                    pages = 56, 
                    latest = True, 
                    data = [
                        buybtcpay.models.approval_entity.ApprovalEntity(
                            id = '', 
                            create_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            applicant_id = '', 
                            approval_status = 0, 
                            approval_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            approver_id = '', 
                            approval_comment = '', 
                            approval_type = 0, 
                            business_id = '', 
                            apply_content = '', 
                            bill_ids = [
                                56
                                ], )
                        ], )
            )
        else:
            return PayResponsePaginationApprovalEntity(
        )
        """

    def testPayResponsePaginationApprovalEntity(self):
        """Test PayResponsePaginationApprovalEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
