# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.pay_pagination_merchant_wallet_entity import PayPaginationMerchantWalletEntity

class TestPayPaginationMerchantWalletEntity(unittest.TestCase):
    """PayPaginationMerchantWalletEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayPaginationMerchantWalletEntity:
        """Test PayPaginationMerchantWalletEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayPaginationMerchantWalletEntity`
        """
        model = PayPaginationMerchantWalletEntity()
        if include_optional:
            return PayPaginationMerchantWalletEntity(
                total = 56,
                current = 56,
                size = 56,
                pages = 56,
                latest = True,
                data = [
                    buybtcpay.models.merchant_wallet_entity.MerchantWalletEntity(
                        id = '', 
                        create_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        merchant_id = '', 
                        type = '1', 
                        available = buybtcpay.models.buy_btc_money_json_value.BuyBtcMoneyJsonValue(
                            amount = '', 
                            currency = '', ), 
                        frozen = buybtcpay.models.buy_btc_money_json_value.BuyBtcMoneyJsonValue(
                            amount = '', 
                            currency = '', ), 
                        version = 56, )
                    ]
            )
        else:
            return PayPaginationMerchantWalletEntity(
        )
        """

    def testPayPaginationMerchantWalletEntity(self):
        """Test PayPaginationMerchantWalletEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
