# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.currency_conversion_dto import CurrencyConversionDto

class TestCurrencyConversionDto(unittest.TestCase):
    """CurrencyConversionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CurrencyConversionDto:
        """Test CurrencyConversionDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CurrencyConversionDto`
        """
        model = CurrencyConversionDto()
        if include_optional:
            return CurrencyConversionDto(
                verification = buybtcpay.models.verification.Verification(
                    request_id = '', 
                    otp_code = '', 
                    otp_type = '', ),
                request_time = '40123456789101112',
                version = 'v4.072888001528021798096225500850762068629',
                nonce = 'G012345678910111213141516171819202122232425262728293031',
                payer = '',
                payee = '',
                source_currency = 'NGN',
                target_currency = 'NGN',
                amount = '',
                time_id = '',
                note = ''
            )
        else:
            return CurrencyConversionDto(
                request_time = '40123456789101112',
                version = 'v4.072888001528021798096225500850762068629',
                nonce = 'G012345678910111213141516171819202122232425262728293031',
                payer = '',
                payee = '',
                source_currency = 'NGN',
                target_currency = 'NGN',
                amount = '',
                time_id = '',
        )
        """

    def testCurrencyConversionDto(self):
        """Test CurrencyConversionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
