# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.create_merchant_recharge_approval_dto import CreateMerchantRechargeApprovalDto

class TestCreateMerchantRechargeApprovalDto(unittest.TestCase):
    """CreateMerchantRechargeApprovalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMerchantRechargeApprovalDto:
        """Test CreateMerchantRechargeApprovalDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMerchantRechargeApprovalDto`
        """
        model = CreateMerchantRechargeApprovalDto()
        if include_optional:
            return CreateMerchantRechargeApprovalDto(
                amount = '',
                wallet_id = '',
                note = '',
                dmerchant_id = ''
            )
        else:
            return CreateMerchantRechargeApprovalDto(
                amount = '',
                wallet_id = '',
        )
        """

    def testCreateMerchantRechargeApprovalDto(self):
        """Test CreateMerchantRechargeApprovalDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
