# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.api.open_bank_account_api import OpenBankAccountApi


class TestOpenBankAccountApi(unittest.TestCase):
    """OpenBankAccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenBankAccountApi()

    def tearDown(self) -> None:
        pass

    def test_query_bank_account(self) -> None:
        """Test case for query_bank_account

        查询银行账户信息
        """
        pass


if __name__ == '__main__':
    unittest.main()
