# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.api.open_merchant_recharge_api import OpenMerchantRechargeApi


class TestOpenMerchantRechargeApi(unittest.TestCase):
    """OpenMerchantRechargeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenMerchantRechargeApi()

    def tearDown(self) -> None:
        pass

    def test_create1(self) -> None:
        """Test case for create1

        创建充值审批单
        """
        pass


if __name__ == '__main__':
    unittest.main()
