# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from buybtcpay.models.virtual_account_top_up_notify_response import VirtualAccountTopUpNotifyResponse

class TestVirtualAccountTopUpNotifyResponse(unittest.TestCase):
    """VirtualAccountTopUpNotifyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VirtualAccountTopUpNotifyResponse:
        """Test VirtualAccountTopUpNotifyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VirtualAccountTopUpNotifyResponse`
        """
        model = VirtualAccountTopUpNotifyResponse()
        if include_optional:
            return VirtualAccountTopUpNotifyResponse(
                order_no = '',
                order_status = '0',
                created_time = 56,
                update_time = 56,
                currency = 'NGN',
                order_amount = 56,
                reference = '',
                payer_account_no = '',
                payer_account_name = '',
                payer_bank_name = '',
                virtual_account_no = '',
                virtual_account_name = '',
                account_reference = '',
                session_id = '',
                sign = ''
            )
        else:
            return VirtualAccountTopUpNotifyResponse(
        )
        """

    def testVirtualAccountTopUpNotifyResponse(self):
        """Test VirtualAccountTopUpNotifyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
