# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from buybtcpay.models.byte_string import ByteString
from buybtcpay.models.unknown_field_set import UnknownFieldSet
from typing import Optional, Set
from typing_extensions import Self

class EnumDescriptorProto(BaseModel):
    """
    EnumDescriptorProto
    """ # noqa: E501
    unknown_fields: Optional[UnknownFieldSet] = Field(default=None, alias="unknownFields")
    reserved_range_list: Optional[List[EnumReservedRange]] = Field(default=None, alias="reservedRangeList")
    reserved_name_list: Optional[List[str]] = Field(default=None, alias="reservedNameList")
    options_or_builder: Optional[EnumOptionsOrBuilder] = Field(default=None, alias="optionsOrBuilder")
    reserved_range_or_builder_list: Optional[List[EnumReservedRangeOrBuilder]] = Field(default=None, alias="reservedRangeOrBuilderList")
    reserved_range_count: Optional[StrictInt] = Field(default=None, alias="reservedRangeCount")
    reserved_name_count: Optional[StrictInt] = Field(default=None, alias="reservedNameCount")
    value_count: Optional[StrictInt] = Field(default=None, alias="valueCount")
    value_list: Optional[List[EnumValueDescriptorProto]] = Field(default=None, alias="valueList")
    value_or_builder_list: Optional[List[EnumValueDescriptorProtoOrBuilder]] = Field(default=None, alias="valueOrBuilderList")
    initialized: Optional[StrictBool] = None
    name: Optional[StrictStr] = None
    options: Optional[EnumOptions] = None
    serialized_size: Optional[StrictInt] = Field(default=None, alias="serializedSize")
    parser_for_type: Optional[Dict[str, Any]] = Field(default=None, alias="parserForType")
    default_instance_for_type: Optional[EnumDescriptorProto] = Field(default=None, alias="defaultInstanceForType")
    name_bytes: Optional[ByteString] = Field(default=None, alias="nameBytes")
    initialization_error_string: Optional[StrictStr] = Field(default=None, alias="initializationErrorString")
    descriptor_for_type: Optional[Descriptor] = Field(default=None, alias="descriptorForType")
    all_fields: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, alias="allFields")
    memoized_serialized_size: Optional[StrictInt] = Field(default=None, alias="memoizedSerializedSize")
    __properties: ClassVar[List[str]] = ["unknownFields", "reservedRangeList", "reservedNameList", "optionsOrBuilder", "reservedRangeOrBuilderList", "reservedRangeCount", "reservedNameCount", "valueCount", "valueList", "valueOrBuilderList", "initialized", "name", "options", "serializedSize", "parserForType", "defaultInstanceForType", "nameBytes", "initializationErrorString", "descriptorForType", "allFields", "memoizedSerializedSize"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnumDescriptorProto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of unknown_fields
        if self.unknown_fields:
            _dict['unknownFields'] = self.unknown_fields.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in reserved_range_list (list)
        _items = []
        if self.reserved_range_list:
            for _item_reserved_range_list in self.reserved_range_list:
                if _item_reserved_range_list:
                    _items.append(_item_reserved_range_list.to_dict())
            _dict['reservedRangeList'] = _items
        # override the default output from pydantic by calling `to_dict()` of options_or_builder
        if self.options_or_builder:
            _dict['optionsOrBuilder'] = self.options_or_builder.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in reserved_range_or_builder_list (list)
        _items = []
        if self.reserved_range_or_builder_list:
            for _item_reserved_range_or_builder_list in self.reserved_range_or_builder_list:
                if _item_reserved_range_or_builder_list:
                    _items.append(_item_reserved_range_or_builder_list.to_dict())
            _dict['reservedRangeOrBuilderList'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in value_list (list)
        _items = []
        if self.value_list:
            for _item_value_list in self.value_list:
                if _item_value_list:
                    _items.append(_item_value_list.to_dict())
            _dict['valueList'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in value_or_builder_list (list)
        _items = []
        if self.value_or_builder_list:
            for _item_value_or_builder_list in self.value_or_builder_list:
                if _item_value_or_builder_list:
                    _items.append(_item_value_or_builder_list.to_dict())
            _dict['valueOrBuilderList'] = _items
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['options'] = self.options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of default_instance_for_type
        if self.default_instance_for_type:
            _dict['defaultInstanceForType'] = self.default_instance_for_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of name_bytes
        if self.name_bytes:
            _dict['nameBytes'] = self.name_bytes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of descriptor_for_type
        if self.descriptor_for_type:
            _dict['descriptorForType'] = self.descriptor_for_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnumDescriptorProto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "unknownFields": UnknownFieldSet.from_dict(obj["unknownFields"]) if obj.get("unknownFields") is not None else None,
            "reservedRangeList": [EnumReservedRange.from_dict(_item) for _item in obj["reservedRangeList"]] if obj.get("reservedRangeList") is not None else None,
            "optionsOrBuilder": EnumOptionsOrBuilder.from_dict(obj["optionsOrBuilder"]) if obj.get("optionsOrBuilder") is not None else None,
            "reservedRangeOrBuilderList": [EnumReservedRangeOrBuilder.from_dict(_item) for _item in obj["reservedRangeOrBuilderList"]] if obj.get("reservedRangeOrBuilderList") is not None else None,
            "reservedRangeCount": obj.get("reservedRangeCount"),
            "reservedNameCount": obj.get("reservedNameCount"),
            "valueCount": obj.get("valueCount"),
            "valueList": [EnumValueDescriptorProto.from_dict(_item) for _item in obj["valueList"]] if obj.get("valueList") is not None else None,
            "valueOrBuilderList": [EnumValueDescriptorProtoOrBuilder.from_dict(_item) for _item in obj["valueOrBuilderList"]] if obj.get("valueOrBuilderList") is not None else None,
            "initialized": obj.get("initialized"),
            "name": obj.get("name"),
            "options": EnumOptions.from_dict(obj["options"]) if obj.get("options") is not None else None,
            "serializedSize": obj.get("serializedSize"),
            "parserForType": obj.get("parserForType"),
            "defaultInstanceForType": EnumDescriptorProto.from_dict(obj["defaultInstanceForType"]) if obj.get("defaultInstanceForType") is not None else None,
            "nameBytes": ByteString.from_dict(obj["nameBytes"]) if obj.get("nameBytes") is not None else None,
            "initializationErrorString": obj.get("initializationErrorString"),
            "descriptorForType": Descriptor.from_dict(obj["descriptorForType"]) if obj.get("descriptorForType") is not None else None,
            "allFields": obj.get("allFields"),
            "memoizedSerializedSize": obj.get("memoizedSerializedSize")
        })
        return _obj

from buybtcpay.models.descriptor import Descriptor
from buybtcpay.models.enum_options import EnumOptions
from buybtcpay.models.enum_options_or_builder import EnumOptionsOrBuilder
from buybtcpay.models.enum_reserved_range import EnumReservedRange
from buybtcpay.models.enum_reserved_range_or_builder import EnumReservedRangeOrBuilder
from buybtcpay.models.enum_value_descriptor_proto import EnumValueDescriptorProto
from buybtcpay.models.enum_value_descriptor_proto_or_builder import EnumValueDescriptorProtoOrBuilder
# TODO: Rewrite to not use raise_errors
EnumDescriptorProto.model_rebuild(raise_errors=False)

