# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PalmPayVirtualAccountOrderRechargeQuery(BaseModel):
    """
    查询条件
    """ # noqa: E501
    id: Optional[StrictStr] = None
    order_by_create_at: Optional[StrictStr] = Field(default=None, alias="orderByCreateAt")
    create_at_since: Optional[StrictStr] = Field(default=None, alias="createAtSince")
    create_at_until: Optional[StrictStr] = Field(default=None, alias="createAtUntil")
    order_no: Optional[StrictStr] = Field(default=None, alias="orderNo")
    order_currency: Optional[StrictStr] = Field(default=None, description="货币类型", alias="orderCurrency")
    order_amount: Optional[List[StrictStr]] = Field(default=None, description="订单金额区间", alias="orderAmount")
    recharge_merchant_id: Optional[StrictStr] = Field(default=None, alias="rechargeMerchantId")
    recharge_business_id: Optional[StrictStr] = Field(default=None, alias="rechargeBusinessId")
    recharge_status: Optional[StrictInt] = Field(default=None, description="0: Init, 1: Success, 2: Failed, 3: Closed, 4: Refunded", alias="rechargeStatus")
    __properties: ClassVar[List[str]] = ["id", "orderByCreateAt", "createAtSince", "createAtUntil", "orderNo", "orderCurrency", "orderAmount", "rechargeMerchantId", "rechargeBusinessId", "rechargeStatus"]

    @field_validator('order_currency')
    def order_currency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NGN', 'GHS', 'ETH', 'BTC', 'USDT']):
            raise ValueError("must be one of enum values ('NGN', 'GHS', 'ETH', 'BTC', 'USDT')")
        return value

    @field_validator('recharge_status')
    def recharge_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1, 2, 3, 4]):
            raise ValueError("must be one of enum values (0, 1, 2, 3, 4)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PalmPayVirtualAccountOrderRechargeQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PalmPayVirtualAccountOrderRechargeQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "orderByCreateAt": obj.get("orderByCreateAt"),
            "createAtSince": obj.get("createAtSince"),
            "createAtUntil": obj.get("createAtUntil"),
            "orderNo": obj.get("orderNo"),
            "orderCurrency": obj.get("orderCurrency"),
            "orderAmount": obj.get("orderAmount"),
            "rechargeMerchantId": obj.get("rechargeMerchantId"),
            "rechargeBusinessId": obj.get("rechargeBusinessId"),
            "rechargeStatus": obj.get("rechargeStatus")
        })
        return _obj


