# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PalmPayVirtualAccountEntity(BaseModel):
    """
    PalmPay虚拟账户
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="ID")
    create_at: Optional[datetime] = Field(default=None, alias="createAt")
    update_at: Optional[datetime] = Field(default=None, alias="updateAt")
    virtual_account_name: Optional[StrictStr] = Field(default=None, description="账户名称", alias="virtualAccountName")
    virtual_account_no: Optional[StrictStr] = Field(default=None, description="账号", alias="virtualAccountNo")
    account_status: Optional[StrictStr] = Field(default=None, description="Disabled: DISABLED, Enabled: ENABLED, Deleted: DELETED", alias="accountStatus")
    identity_type: Optional[StrictStr] = Field(default=None, description="personal: PERSIONAL, company: COMPANY", alias="identityType")
    license_number: Optional[StrictStr] = Field(default=None, description="证件号码", alias="licenseNumber")
    email: Optional[StrictStr] = Field(default=None, description="使用者邮箱")
    customer_name: Optional[StrictStr] = Field(default=None, description="使用者姓名", alias="customerName")
    account_reference: Optional[StrictStr] = Field(default=None, description="备注", alias="accountReference")
    __properties: ClassVar[List[str]] = ["id", "createAt", "updateAt", "virtualAccountName", "virtualAccountNo", "accountStatus", "identityType", "licenseNumber", "email", "customerName", "accountReference"]

    @field_validator('account_status')
    def account_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Disabled', 'Enabled', 'Deleted']):
            raise ValueError("must be one of enum values ('Disabled', 'Enabled', 'Deleted')")
        return value

    @field_validator('identity_type')
    def identity_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['personal', 'company']):
            raise ValueError("must be one of enum values ('personal', 'company')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PalmPayVirtualAccountEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PalmPayVirtualAccountEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "createAt": obj.get("createAt"),
            "updateAt": obj.get("updateAt"),
            "virtualAccountName": obj.get("virtualAccountName"),
            "virtualAccountNo": obj.get("virtualAccountNo"),
            "accountStatus": obj.get("accountStatus"),
            "identityType": obj.get("identityType"),
            "licenseNumber": obj.get("licenseNumber"),
            "email": obj.get("email"),
            "customerName": obj.get("customerName"),
            "accountReference": obj.get("accountReference")
        })
        return _obj


