# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PaymentOrderPaginationQuery(BaseModel):
    """
    支付单分页查询条件
    """ # noqa: E501
    id: Optional[StrictStr] = None
    order_by_create_at: Optional[StrictStr] = Field(default=None, alias="orderByCreateAt")
    create_at_since: Optional[StrictStr] = Field(default=None, alias="createAtSince")
    create_at_until: Optional[StrictStr] = Field(default=None, alias="createAtUntil")
    order_id: Optional[StrictStr] = Field(default=None, description="订单号", alias="orderId")
    merchant_id: Optional[StrictStr] = Field(default=None, description="所属商户ID", alias="merchantId")
    channel_id: Optional[StrictStr] = Field(default=None, description="支付链路ID", alias="channelId")
    type: Optional[StrictInt] = Field(default=None, description="0: Merchant to merchant, 1: Withdrawal")
    currency: Optional[StrictStr] = Field(default=None, description="NGN: Nigerian Naira, GHS: Ghanaian Cedi, ETH: Ethereum, BTC: Bitcoin, USDT: Tether")
    amount: Optional[List[StrictStr]] = Field(default=None, description="支付金额区间")
    fee: Optional[List[StrictStr]] = Field(default=None, description="手续费")
    order_status: Optional[StrictInt] = Field(default=None, description="0: UNPAID, 1: PAYING, 2: SUCCESS, 3: FAIL, 4: CLOSE, 20: REFUNDED", alias="orderStatus")
    prepayment_order_id: Optional[StrictStr] = Field(default=None, description="预付单号", alias="prepaymentOrderId")
    __properties: ClassVar[List[str]] = ["id", "orderByCreateAt", "createAtSince", "createAtUntil", "orderId", "merchantId", "channelId", "type", "currency", "amount", "fee", "orderStatus", "prepaymentOrderId"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    @field_validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NGN', 'GHS', 'ETH', 'BTC', 'USDT']):
            raise ValueError("must be one of enum values ('NGN', 'GHS', 'ETH', 'BTC', 'USDT')")
        return value

    @field_validator('order_status')
    def order_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1, 2, 3, 4, 20]):
            raise ValueError("must be one of enum values (0, 1, 2, 3, 4, 20)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentOrderPaginationQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentOrderPaginationQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "orderByCreateAt": obj.get("orderByCreateAt"),
            "createAtSince": obj.get("createAtSince"),
            "createAtUntil": obj.get("createAtUntil"),
            "orderId": obj.get("orderId"),
            "merchantId": obj.get("merchantId"),
            "channelId": obj.get("channelId"),
            "type": obj.get("type"),
            "currency": obj.get("currency"),
            "amount": obj.get("amount"),
            "fee": obj.get("fee"),
            "orderStatus": obj.get("orderStatus"),
            "prepaymentOrderId": obj.get("prepaymentOrderId")
        })
        return _obj


