# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from buybtcpay.models.byte_string import ByteString
from buybtcpay.models.descriptor import Descriptor
from buybtcpay.models.raw import Raw
from buybtcpay.models.raw_or_builder import RawOrBuilder
from buybtcpay.models.result import Result
from buybtcpay.models.result_or_builder import ResultOrBuilder
from buybtcpay.models.unknown_field_set import UnknownFieldSet
from typing import Optional, Set
from typing_extensions import Self

class Transaction(BaseModel):
    """
    Transaction
    """ # noqa: E501
    unknown_fields: Optional[UnknownFieldSet] = Field(default=None, alias="unknownFields")
    initialized: Optional[StrictBool] = None
    raw_data: Optional[Raw] = Field(default=None, alias="rawData")
    serialized_size: Optional[StrictInt] = Field(default=None, alias="serializedSize")
    ret_count: Optional[StrictInt] = Field(default=None, alias="retCount")
    parser_for_type: Optional[Dict[str, Any]] = Field(default=None, alias="parserForType")
    default_instance_for_type: Optional[Transaction] = Field(default=None, alias="defaultInstanceForType")
    raw_data_or_builder: Optional[RawOrBuilder] = Field(default=None, alias="rawDataOrBuilder")
    signature_list: Optional[List[ByteString]] = Field(default=None, alias="signatureList")
    signature_count: Optional[StrictInt] = Field(default=None, alias="signatureCount")
    ret_list: Optional[List[Result]] = Field(default=None, alias="retList")
    ret_or_builder_list: Optional[List[ResultOrBuilder]] = Field(default=None, alias="retOrBuilderList")
    initialization_error_string: Optional[StrictStr] = Field(default=None, alias="initializationErrorString")
    descriptor_for_type: Optional[Descriptor] = Field(default=None, alias="descriptorForType")
    all_fields: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, alias="allFields")
    memoized_serialized_size: Optional[StrictInt] = Field(default=None, alias="memoizedSerializedSize")
    __properties: ClassVar[List[str]] = ["unknownFields", "initialized", "rawData", "serializedSize", "retCount", "parserForType", "defaultInstanceForType", "rawDataOrBuilder", "signatureList", "signatureCount", "retList", "retOrBuilderList", "initializationErrorString", "descriptorForType", "allFields", "memoizedSerializedSize"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Transaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of unknown_fields
        if self.unknown_fields:
            _dict['unknownFields'] = self.unknown_fields.to_dict()
        # override the default output from pydantic by calling `to_dict()` of raw_data
        if self.raw_data:
            _dict['rawData'] = self.raw_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of default_instance_for_type
        if self.default_instance_for_type:
            _dict['defaultInstanceForType'] = self.default_instance_for_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of raw_data_or_builder
        if self.raw_data_or_builder:
            _dict['rawDataOrBuilder'] = self.raw_data_or_builder.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in signature_list (list)
        _items = []
        if self.signature_list:
            for _item_signature_list in self.signature_list:
                if _item_signature_list:
                    _items.append(_item_signature_list.to_dict())
            _dict['signatureList'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ret_list (list)
        _items = []
        if self.ret_list:
            for _item_ret_list in self.ret_list:
                if _item_ret_list:
                    _items.append(_item_ret_list.to_dict())
            _dict['retList'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ret_or_builder_list (list)
        _items = []
        if self.ret_or_builder_list:
            for _item_ret_or_builder_list in self.ret_or_builder_list:
                if _item_ret_or_builder_list:
                    _items.append(_item_ret_or_builder_list.to_dict())
            _dict['retOrBuilderList'] = _items
        # override the default output from pydantic by calling `to_dict()` of descriptor_for_type
        if self.descriptor_for_type:
            _dict['descriptorForType'] = self.descriptor_for_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Transaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "unknownFields": UnknownFieldSet.from_dict(obj["unknownFields"]) if obj.get("unknownFields") is not None else None,
            "initialized": obj.get("initialized"),
            "rawData": Raw.from_dict(obj["rawData"]) if obj.get("rawData") is not None else None,
            "serializedSize": obj.get("serializedSize"),
            "retCount": obj.get("retCount"),
            "parserForType": obj.get("parserForType"),
            "defaultInstanceForType": Transaction.from_dict(obj["defaultInstanceForType"]) if obj.get("defaultInstanceForType") is not None else None,
            "rawDataOrBuilder": RawOrBuilder.from_dict(obj["rawDataOrBuilder"]) if obj.get("rawDataOrBuilder") is not None else None,
            "signatureList": [ByteString.from_dict(_item) for _item in obj["signatureList"]] if obj.get("signatureList") is not None else None,
            "signatureCount": obj.get("signatureCount"),
            "retList": [Result.from_dict(_item) for _item in obj["retList"]] if obj.get("retList") is not None else None,
            "retOrBuilderList": [ResultOrBuilder.from_dict(_item) for _item in obj["retOrBuilderList"]] if obj.get("retOrBuilderList") is not None else None,
            "initializationErrorString": obj.get("initializationErrorString"),
            "descriptorForType": Descriptor.from_dict(obj["descriptorForType"]) if obj.get("descriptorForType") is not None else None,
            "allFields": obj.get("allFields"),
            "memoizedSerializedSize": obj.get("memoizedSerializedSize")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
Transaction.model_rebuild(raise_errors=False)

