# coding: utf-8

"""
    pay.buybtc123.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class VirtualAccountPaginationQuery(BaseModel):
    """
    查询条件
    """ # noqa: E501
    id: Optional[StrictStr] = None
    order_by_create_at: Optional[StrictStr] = Field(default=None, alias="orderByCreateAt")
    create_at_since: Optional[StrictStr] = Field(default=None, alias="createAtSince")
    create_at_until: Optional[StrictStr] = Field(default=None, alias="createAtUntil")
    merchant_ids: Optional[Annotated[List[StrictStr], Field(min_length=1, max_length=100)]] = Field(default=None, description="商户ID列表", alias="merchantIds")
    account_status: Optional[StrictInt] = Field(default=None, description="0: NORMAL, 1: DISABLED", alias="accountStatus")
    parent_merchant_id: Optional[StrictStr] = Field(default=None, description="父商户ID", alias="parentMerchantId")
    __properties: ClassVar[List[str]] = ["id", "orderByCreateAt", "createAtSince", "createAtUntil", "merchantIds", "accountStatus", "parentMerchantId"]

    @field_validator('account_status')
    def account_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 1]):
            raise ValueError("must be one of enum values (0, 1)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VirtualAccountPaginationQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VirtualAccountPaginationQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "orderByCreateAt": obj.get("orderByCreateAt"),
            "createAtSince": obj.get("createAtSince"),
            "createAtUntil": obj.get("createAtUntil"),
            "merchantIds": obj.get("merchantIds"),
            "accountStatus": obj.get("accountStatus"),
            "parentMerchantId": obj.get("parentMerchantId")
        })
        return _obj


